main_practice/urls.py
from django.urls import path

from .views import (MainView)

app_name = 'main_practice'

urlpatterns = [
    path('input', MainView.as_view(), name='input'),
]

practice_1/urls.py
from django.contrib import admin
from django.urls import path, include
import main_practice
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_practice.urls'),)
]

if settings.DEBUG == True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main_practice/models.py
from django.db import models

# Create your models here.

main_practice/views.py
from django.shortcuts import render
from django.views.generic import View
from django.shortcuts import render
import numpy as np
import matplotlib.pyplot as plt


# Create your views here.

class MainView(View):

    def get(self, request):
        print(request)
        return render(request, 'input.html')

    def post(self, request):
        number_of_a_data = int(request.POST['number_of_data_a'])
        a_mean = [float(request.POST['x1_mean_a']), float(request.POST['x2_mean_a'])]
        a_cov = [[float(request.POST['x1_var_a']), float(request.POST['x1x2_cov_a'])],
                 [float(request.POST['x2x1_cov_a']), float(request.POST['x2_var_a'])]]
        a_x1, a_x2 = np.random.multivariate_normal(a_mean, a_cov, number_of_a_data).T
        a_data = []
        for i in range(0, number_of_a_data):
            a_data.append({'x': a_x1[i], 'y': a_x2[i]})

        number_of_b_data = int(request.POST['number_of_data_b'])
        b_mean = [float(request.POST['x1_mean_b']), float(request.POST['x2_mean_b'])]
        b_cov = [[float(request.POST['x1_var_b']), float(request.POST['x1x2_cov_b'])],
                 [float(request.POST['x2x1_cov_b']), float(request.POST['x2_var_b'])]]
        b_x1, b_x2 = np.random.multivariate_normal(b_mean, b_cov, number_of_b_data).T
        b_data = []
        for i in range(0, number_of_b_data):
            b_data.append({'x': b_x1[i], 'y': b_x2[i]})

        epoch = int(request.POST['max_step'])
        w = []
        p_w0, p_w1, p_w2 = 0, 0, 0
        h_bias, h_w1, h_w2 = 0, 0, 0
        p_x0 = 1
        for step in range(0, epoch):
            p_t = -1
            h_y = 1
            for j in range(0, number_of_a_data):
                # Perceptron
                i = p_w0 + p_w1 * a_x1[j] + p_w2 * a_x2[j]
                if i >= 0:
                    y = 1
                else:
                    y = 0
                p_w0 += (p_t - y) * p_x0
                p_w1 += (p_t - y) * a_x1[j]
                p_w2 += (p_t - y) * a_x2[j]

                # Hebb
                if a_x1[j] >= 0:
                    h_x1 = 1
                else:
                    h_x1 = -1
                if a_x2[j] >= 0:
                    h_x2 = 1
                else:
                    h_x2 = -1
                h_w1 += h_x1 * h_y
                h_w2 += h_x2 * h_y
                h_bias += h_y

            p_t = 1
            h_y = -1
            for j in range(0, number_of_b_data):
                # perceptron
                i = p_w0 + p_w1 * b_x1[j] + p_w2 * b_x2[j]
                if i >= 0:
                    y = 1
                else:
                    y = 0
                p_w0 += (p_t - y) * p_x0
                p_w1 += (p_t - y) * b_x1[j]
                p_w2 += (p_t - y) * b_x2[j]

                # Hebb
                if b_x1[j] >= 0:
                    h_x1 = 1
                else:
                    h_x1 = -1
                if b_x2[j] >= 0:
                    h_x2 = 1
                else:
                    h_x2 = -1
                h_w1 += h_x1 * h_y
                h_w2 += h_x2 * h_y
                h_bias += h_y

            min_x1 = min(a_x1.min(), b_x1.min())
            max_x1 = max(a_x1.max(), b_x1.max())

            p_min_x2 = (-1) * ((p_w0 + min_x1 * p_w1) / p_w2)
            p_max_x2 = (-1) * ((p_w0 + max_x1 * p_w1) / p_w2)

            h_min_x2 = (-1) * (((-1) * h_bias + min_x1 * h_w1) / h_w2)
            h_max_x2 = (-1) * (((-1) * h_bias + max_x1 * h_w1) / h_w2)
            w.append({
                'perceptron': {'step': step + 1, 'w0': p_w0, 'w1': p_w1, 'w2': p_w2,
                               'point_data': [{'x': min_x1, 'y': p_min_x2}, {'x': max_x1, 'y': p_max_x2}]},
                'hebb': {'step': step + 1, 'bias': h_bias, 'w1': h_w1, 'w2': h_w2,
                         'point_data': [{'x': min_x1, 'y': h_min_x2}, {'x': max_x1, 'y': h_max_x2}]}
            })

        return render(request, 'output.html', {'a_data': a_data, 'b_data': b_data, 'w': w})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="{% static 'js/bootstrap.min.js' %}"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
</head>
<body>
<div class="container" style="background-color:#92f5ff;direction: rtl; text-align: center">
    <div class="row">
        <div class="col-md-12">
            <img src="{% static 'img/IRI-MUT.svg' %}" style="width: 8vw;">
        </div>
    </div>
    <div class="row mt-4 p-3" style="background-color: #004046;color: #fff;box-shadow: 0px 0px 5px black; ">
        <div class="col-md-4">
            استاد: آقای دکتر فخر دانش
        </div>
        <div class="col-md-4">
            دانشجو: مهندس مهدی رحمانی
        </div>
        <div class="col-md-4">
            درس: شبکه های عصبی
        </div>
    </div>
    <div class="row mb-4 mt-2"style="background-color: #007b86;box-shadow: 0px 0px 7px #000000; ">
        <div class="col-md-12">
            <a href="{% url 'main_practice:input' %}">
                <div style="width: 100%; color: #ffffff; ">
                    برای ورود دیتا کلیک کنید
                </div>
            </a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            {% block content %}
            {% endblock %}
        </div>
    </div>
<div class="row mt-4 p-3" style="background-color: #960101;box-shadow: inset 0px 0px 10px black; ">
        <div class="col-md-6">
            <a href="https://gitlab.com/Mahdi_Rahmani/perceptron_hebb" target="_blank">
                <div style="width: 100%; color: #ffffff; ">
                    https://gitlab.com/Mahdi_Rahmani/perceptron_hebb
                </div>
            </a>
        </div>
        <div class="col-md-6">
            <a href="mailto:mahdirahmani1375@gmail.com" target="_blank">
                <div style="width: 100%; color: #ffffff; ">
                    mahdirahmani1375@gmail.com
                </div>
            </a>
        </div>
    </div>
</div>
</body>
</html>

templates/input.html
{% extends 'base.html' %}

{% block content %}
        <form action="{% url 'main_practice:input' %}" method="post">
            {% csrf_token %}
            <div class="row p-3">
                <div class="col-md-4">
                    بردار میانگین دسته اول:
                </div>
                <div class="col-md-4">
                    <input type="text" name="x1_mean_a" placeholder="x1">
                </div>
                <div class="col-md-4">
                    <input type="text" name="x2_mean_a" placeholder="x2">
                </div>
            </div>
            <div class="row p-3">
                <div class="col-md-4">
                    ماتریس کواریانس دسته اول:
                </div>
                <div class="col-md-4">
                    <input type="text" name="x1_var_a" placeholder="x1 var">
                </div>
                <div class="col-md-4">
                    <input type="text" name="x1x2_cov_a" placeholder="x1x2 cov">
                </div>
            </div>
            <div class="row p-3">
                <div class="col-md-4">
                </div>
                <div class="col-md-4">
                    <input type="text" name="x2x1_cov_a" placeholder="x2x1 cov">
                </div>
                <div class="col-md-4">
                    <input type="text" name="x2_var_a" placeholder="x2 var">
                </div>
            </div>
            <div class="row p-3">
                <div class="col-md-4">
                    بردار میانگین دسته دوم:
                </div>
                <div class="col-md-4">
                    <input type="text" name="x1_mean_b" placeholder="x1">
                </div>
                <div class="col-md-4">
                    <input type="text" name="x2_mean_b" placeholder="x2">
                </div>
            </div>
            <div class="row p-3">
                <div class="col-md-4">
                    ماتریس کواریانس دسته دوم:
                </div>
                <div class="col-md-4">
                    <input type="text" name="x1_var_b" placeholder="x1 var">
                </div>
                <div class="col-md-4">
                    <input type="text" name="x1x2_cov_b" placeholder="x1x2 cov">
                </div>
            </div>
            <div class="row p-3">
                <div class="col-md-4">
                </div>
                <div class="col-md-4">
                    <input type="text" name="x2x1_cov_b" placeholder="x2x1 cov">
                </div>
                <div class="col-md-4">
                    <input type="text" name="x2_var_b" placeholder="x2 var">
                </div>
            </div>
            <div class="row p-3">
                <div class="col-md-4">
                    تعداد داده های هر دسته:
                </div>
                <div class="col-md-4">
                    <input type="number" name="number_of_data_a" placeholder="تعداد داده های دسته اول">
                </div>
                <div class="col-md-4">
                    <input type="number" name="number_of_data_b" placeholder="تعداد داده های دسته دوم">
                </div>
            </div>
            <div class="row p-3">
                <div class="col-md-4">
                    حداکثر تعداد گام:
                </div>
                <div class="col-md-4">
                    <input type="number" name="max_step" placeholder="حداکثر تعداد گام">
                </div>
                <div class="col-md-4">
                    <input class="btn btn-success w-50" type="submit" value="اجرا">
                </div>
            </div>
        </form>

{% endblock %}

templates/output.html
{% extends 'base.html' %}

{% block content %}
    <div class="row p-3">
        <div class="col-md-6">
            <h1>Perceptron</h1>
        </div>
        <div class="col-md-6">
            <h1>Hebb</h1>
        </div>
    </div>
    <div class="row p-3">
        <div class="col-md-6">
            <canvas id="perceptron_chart"></canvas>
        </div>
        <div class="col-md-6">
            <canvas id="hebb_chart"></canvas>
        </div>
    </div>
    <div class="row p-3">
        <div class="col-md-6">
            <table class="table">
                <thead>
                <tr>
                    <th>step</th>
                    <th>w0</th>
                    <th>w1</th>
                    <th>w2</th>
                </tr>
                </thead>
                <tbody>
                {% for i in w %}
                    <tr>
                        <td>{{ i.perceptron.step }}</td>
                        <td>{{ i.perceptron.w0 }}</td>
                        <td>{{ i.perceptron.w1 }}</td>
                        <td>{{ i.perceptron.w2 }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-md-6">
            <table class="table">
                <thead>
                <tr>
                    <th>step</th>
                    <th>bias</th>
                    <th>w1</th>
                    <th>w2</th>
                </tr>
                </thead>
                <tbody>
                {% for i in w %}
                    <tr>
                        <td>{{ i.hebb.step }}</td>
                        <td>{{ i.hebb.bias }}</td>
                        <td>{{ i.hebb.w1 }}</td>
                        <td>{{ i.hebb.w2 }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <canvas id="myChart"></canvas>

    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
    <script>
        var ctx = document.getElementById('perceptron_chart');
        var dataset = []
        dataset.push({
            data:  {{ a_data|safe }},
            pointBackgroundColor: 'rgba(255,0,0,0.1)',
            pointBorderColor: 'rgba(255,0,0,0.3)',
            label: 'Class A',
            backgroundColor: 'rgba(255,0,0)',
        })
        dataset.push({
            data:  {{ b_data|safe }},
            pointBackgroundColor: 'rgba(0,0,255,0.1)',
            pointBorderColor: 'rgb(0,0,255,0.3)',
            label: 'Class B',
            backgroundColor: 'rgba(0,0,255)',
        })
        var i;
        w_length =
        {{ w|safe }}.length
        w_length_step = Math.floor(w_length / 4.2)
        var line_color = 255 / w_length;
        for (i = 0; i < w_length; i = i + w_length_step) {
            color_number = line_color * (i + 1)
            rgb_color = "rgb(" + color_number + "," + color_number + "," + color_number + ")"
            point_data = {{ w|safe }}[i].perceptron.point_data
            dataset.push({
                type: 'line',
                label: 'step_' + (i + 1),
                data: point_data,
                fill: false,
                backgroundColor: rgb_color,
                borderColor: rgb_color,
                pointRadius: 0
            })
        }
        var scatterChart = new Chart(ctx, {
            type: 'scatter',
            data: {
                datasets: dataset
            },
            options: {
                scales: {
                    xAxes: [{
                        type: 'linear',
                        position: 'bottom'
                    }]
                }
            }
        });

        var ctx = document.getElementById('hebb_chart');
        var dataset = []
        dataset.push({
            data:  {{ a_data|safe }},
            pointBackgroundColor: 'rgba(255,0,0,0.1)',
            pointBorderColor: 'rgba(255,0,0,0.3)',
            label: 'Class A',
            backgroundColor: 'rgba(255,0,0)',
        })
        dataset.push({
            data:  {{ b_data|safe }},
            pointBackgroundColor: 'rgba(0,0,255,0.1)',
            pointBorderColor: 'rgb(0,0,255,0.3)',
            label: 'Class B',
            backgroundColor: 'rgba(0,0,255)',
        })
        for (i = 0; i < w_length; i = i + w_length_step) {
            color_number = line_color * (i + 1)
            rgb_color = "rgb(" + color_number + "," + color_number + "," + color_number + ")"
            point_data = {{ w|safe }}[i].hebb.point_data
            dataset.push({
                type: 'line',
                label: 'step_' + (i + 1),
                data: point_data,
                fill: false,
                backgroundColor: rgb_color,
                borderColor: rgb_color,
                pointRadius: 0
            })
        }
        var scatterChart = new Chart(ctx, {
            type: 'scatter',
            data: {
                datasets: dataset
            },
            options: {
                scales: {
                    xAxes: [{
                        type: 'linear',
                        position: 'bottom'
                    }]
                }
            }
        });

    </script>
{% endblock %}